schema_version: 1

context:
  name: onnx-cse
  version: "0.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/onnx_cse-${{ version }}.tar.gz
  sha256: d8d91fc0ed751666b925f8908013a31cb7b517e5459ee6f3324477b513c0eded

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - python-xxhash
    - typing_extensions
    - onnx

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - onnx_cse
      pip_check: true

about:
  summary: Common subexpression elimination for ONNX graphs
  homepage: https://github.com/cbourjau/onnx-cse
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
